DoAnTotNghiep/ViewModels/AuthorizeViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoAnTotNghiep.ViewModels
{
    public class RefreshToken
    {
        public string Action { get; set;} = string.Empty;
        public string? UserAccess { get; set; } = string.Empty;
        public string? Email { get; set; } = string.Empty;
        public string OldToken { get; set; } = string.Empty;
    }
}

DoAnTotNghiep/Controllers/AuthorizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnTotNghiep.Data;
using DoAnTotNghiep.Entity;
using DoAnTotNghiep.ViewModels;
using DoAnTotNghiep.Modules;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Security.Claims;
using DoAnTotNghiep.Enum;
using NuGet.Protocol;
using System.Configuration;
using System.IdentityModel.Tokens.Jwt;
using NuGet.Common;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using static System.Net.WebRequestMethods;
using System.Composition;
using DoAnTotNghiep.Service;
using DoAnTotNghiep.Response;
using static QRCoder.PayloadGenerator;
using Org.BouncyCastle.Utilities.Collections;
using System.Runtime.Intrinsics.X86;

namespace DoAnTotNghiep.Controllers
{
    public class AuthorizeController: BaseController
    {
        //xong rồi
        private readonly DoAnTotNghiepContext _context;
        private readonly IConfiguration _configuration;
        private readonly IUserService _userService;

        public AuthorizeController(DoAnTotNghiepContext context, 
                                    IConfiguration configuration,
                                    IHostEnvironment environment,
                                    IUserService userService): base(environment)
        {
            _context = context;
            _configuration = configuration;
            _userService = userService;
        }

        public async Task<IActionResult> SignIn()
        {
            var role = this.GetRole();
            if (role == Role.Member)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (role == Role.Admin)
            {
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                await this.SignOutCookie();
            }
            int IdUser = this.GetIdUser();
            if(IdUser != 0)
            {
                this.SetViewData(new DoAnTotNghiepContext(this._context.GetConfig()), IdUser, Crypto.Salt(this._configuration));
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(LoginViewModel loginViewModel)
        {
            return await this.GeneralSignInAsync(loginViewModel, true);
        }
        private async Task SignClaim(List<Claim> claims, string scheme, DateTimeOffset dateTimeOffset)
        {
            var identity = new ClaimsIdentity(claims, scheme);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(
                scheme: scheme,
                principal: principal,
                properties: new AuthenticationProperties()
                {
                    IsPersistent = true,
                    ExpiresUtc = dateTimeOffset
                }).WaitAsync(TimeSpan.FromSeconds(15)
            );
        }
        [HttpPost("/api/SignIn")]
        public async Task<IActionResult> ApiSignInAsync([FromBody] LoginViewModel loginViewModel)
        {
            return await this.GeneralSignInAsync(loginViewModel, false);
        }
        private async Task<IActionResult> GeneralSignInAsync(LoginViewModel loginViewModel, bool isWeb)
        {
            if (ModelState.IsValid)
            {
                var user = this._userService.GetByEmail(loginViewModel.Email);
                if (user != null)
                {
                    if (Crypto.IsPass(loginViewModel.Password, user.Password, user.Salt))
                    {
                        List<Claim> claims = new List<Claim>() {
                            new Claim(ClaimTypes.Name, user.Id.ToString()),
                            new Claim(ClaimTypes.Email, user.Email),
                        };

                        if (user.Role == Role.MemberCode)
                        {
                            claims.Add(new Claim(ClaimTypes.Role, Role.Member));
                        }
                        else
                        {
                            claims.Add(new Claim(ClaimTypes.Role, Role.Admin));
                        }

                        if (isWeb)
                        {
                            await this.SignClaim(claims, Scheme.AuthenticationCookie(), DateTime.UtcNow.AddHours(Cookie.TimeExpireWeb));
                            if(user.Role == Role.AdminCode)
                                return RedirectToAction("Index", "Admin");
                            return RedirectToAction("Index", "Home");
                        }

                        var token = new JwtHelper(this._configuration).GenerateToken(claims);
                        UserInfo.GetEntityRelated(user, this._context);//get Image, numberHouse

                        return Json(new
                        {
                            Status = 200,
                            Message = "Đăng nhập thành công",
                            Data = new
                            {
                                Token = new JwtSecurityTokenHandler().WriteToken(token),
                                Expire = token.ValidTo,
                                UserInfo = new UserInfo(user, Crypto.Salt(this._configuration), this.GetWebsitePath())
                            }
                        });

                    }
                    else
                    {
                        ModelState.AddModelError("PassWord", AuthorizeResponseHttp.InCorrectPassword);
                    }
                }
                else
                {
                    ModelState.AddModelError("", AuthorizeResponseHttp.NotFoundUser);
                }
            }
            if (isWeb)
            {
                return View(loginViewModel);
            }

            return BadRequest(new
            {
                Status = 400,
                Message = this.ModelErrors()
            });
        }

        [HttpGet]
        public IActionResult SignUpCheckMail()
        {
            string role = this.GetRole();
            if (role == Role.UnAuthorize) return View(new RegisterCheckMailViewModel());
            else if (role == Role.Member)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (role == Role.Admin)
            {
                return RedirectToAction("", "Admin");
            }
            return RedirectToAction(nameof(SignUpPassword), new { Email = this.GetEmail() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignUpCheckMail(RegisterCheckMailViewModel registerViewModel)
        {
            return this.GeneralCheckMail(registerViewModel, true);
        }

        [HttpPost("/api/SignUp/CheckMail")]
        public IActionResult ApiCheckMail([FromBody] RegisterCheckMailViewModel registerViewModel)
        {
            return this.GeneralCheckMail(registerViewModel, false);
        }
        private IActionResult GeneralCheckMail(RegisterCheckMailViewModel registerViewModel, bool isWeb)
        {
            if(isWeb && this.GetIdUser() != 0) return NotFound();
            if (ModelState.IsValid)
            {
                if (!this._userService.IsExistEmail(registerViewModel.Email))//không tồn tại
                {
                    if (isWeb)
                    {
                        this.SetCookie("Email", registerViewModel.Email, null);
                        return RedirectToAction(nameof(SignUpPassword), new { Email = registerViewModel.Email });
                    }

                    return Json(new
                    {
                        Status = 200,
                        Message = AuthorizeResponseHttp.EmailValid,
                        Data = new 
                        {
                            isExisted = false
                        }
                    });
                }
                else if(!isWeb)
                {
                    return Json(new
                    {
                        Status = 200,
                        Message = AuthorizeResponseHttp.EmailValid,
                        Data = new
                        {
                            isExisted = true
                        }
                    });
                }
                else
                {
                    ModelState.AddModelError("Email", AuthorizeResponseHttp.EmailUsed);
                }
            }
            if (isWeb) return View(registerViewModel);

            return BadRequest(new
            {
                Status = 400,
                Message = ModelErrors()
            });
        }


        [HttpGet]
        public IActionResult SignUpPassword(string Email)
        {
            string role = this.GetRole();
            if(role == Role.UnAuthorize) return View(new RegisterPasswordViewModel() { Email = Email});
            else if(role == Role.Member)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (role == Role.Admin)
            {
                return RedirectToAction("", "Admin");
            }
            return RedirectToAction(nameof(SignUpOTP));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUpPassword(RegisterPasswordViewModel registerPasswordViewModel)
        {
            if (this.GetIdUser() != 0) return NotFound();
            if (ModelState.IsValid)
            {
                string? email = this.GetCookie("Email");
                if (string.IsNullOrEmpty(email)) email = registerPasswordViewModel.Email;
                if (!this._userService.IsExistEmail(email))
                {

DoAnTotNghiep/Views/Authorize/Forgot.cshtml
@model DoAnTotNghiep.ViewModels.RegisterCheckMailViewModel
@{
    ViewData["Title"] = "Quên mật khẩu";
    Layout = "_LayoutLogin";
}


<!-- Forgot Password -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Quên mật khẩu? 🔒</h4>
        <p class="mb-4">Điền email của bạn đã đăng ký, chúng tôi sẽ cấp lại mật khẩu cho bạn.</p>
        <form id="formAuthentication" class="mb-3" asp-action="Forgot" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="Email" placeholder="Enter your email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Gửi xác nhận</button>
        </form>
        <div class="text-center">
            <a href="@Url.Action("SignIn", "Authorize")" class="d-flex align-items-center justify-content-center">
                <i class="bx bx-chevron-left scaleX-n1-rtl bx-sm"></i>
                Quay lại đăng nhập
            </a>
        </div>
    </div>
</div>
<!-- /Forgot Password -->

DoAnTotNghiep/Views/Authorize/ForgotOTP.cshtml
@model DoAnTotNghiep.ViewModels.RegisterOTPViewModel
@{
    ViewData["Title"] = "Quên mật khẩu";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Xác thực tài khoản</h4>

        <form id="formAuthentication" class="mb-3" asp-action="ForgotOTP" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="OTP" class="form-label">Mã OTP</label>
                <div class="input-timer">
                    <input class="form-control" asp-for="OTP" placeholder="000 - 000" />
                    <span class="timer text-danger">_ : _</span>
                </div>
                <span asp-validation-for="OTP" class="text-danger"></span>
            </div>
            <p class="text-center"><small>Không nhận được? </small><a href="@Url.Action("ForgotResendOTP")" class="fw-bold" id="resend"><small>Gửi lại email</small></a></p>
            <button type="submit" class="btn btn-primary d-grid w-100">Tiếp tục</button>
        </form>
    </div>
</div>

@section Scripts{
    <script src="~/js/Auth/timer.js"></script>
    <script>
        $(document).ready(function(){
            timer('.timer', @(ViewData["timer"] == null ? Html.Raw("120") : Html.Raw(ViewData["timer"])))
        })
    </script>
}

DoAnTotNghiep/Views/Authorize/RefreshPassword.cshtml
@model DoAnTotNghiep.ViewModels.UpdatePasswordViewModel
@{
    ViewData["Title"] = "Cập nhật mật khẩu";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Cập nhật mật khẩu mới</h4>

        <form id="formAuthentication" class="mb-3" asp-action="RefreshPassword" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="Password">Mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           asp-for="Password"
                           class="form-control"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="ConfirmPassword">Xác nhận mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           class="form-control"
                           asp-for="ConfirmPassword"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Hoàn tất</button>
        </form>
    </div>
</div>

DoAnTotNghiep/Views/Authorize/SignIn.cshtml
@model DoAnTotNghiep.ViewModels.LoginViewModel
@{
    ViewData["Title"] = "Đăng nhập";
    Layout = "_LayoutLogin";
}

<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Chào mừng bạn trở lại! 👋</h4>
        <p class="mb-4">Hãy đăng nhập và tận hưởng dịch vụ của chúng tôi.</p>

        <form id="formAuthentication" class="mb-3" asp-action="SignIn" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text"
                       class="form-control"
                       asp-for="Email"
                       placeholder="Điền email của bạn"
                       autofocus />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <div class="d-flex justify-content-between">
                    <label class="form-label" asp-for="Password">Mật khẩu</label>
                    <a href="@Url.Action("Forgot", "Authorize")">
                        <small>Quên mật khẩu?</small>
                    </a>
                </div>
                <div class="input-group input-group-merge">
                    <input type="password"
                           class="form-control"
                           asp-for="Password"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary d-grid w-100" type="submit">Đăng nhập</button>
                <a href="@Url.Action("Index", "Home")" class="btn btn-outline-primary d-grid w-100 mt-2 text-decoration-none">Trang chủ</a>
            </div>
        </form>

        <p class="text-center">
            <span>Bạn có tài khoản chưa?</span>
            <a href="@Url.Action("SignUpCheckMail", "Authorize")">
                <span>Tạo tài khoản mới</span>
            </a>
        </p>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoAnTotNghiep/Views/Authorize/SignUp.cshtml
@model DoAnTotNghiep.ViewModels.RegisterViewModel
@{
    ViewData["Title"] = "Đăng ký";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Chào mừng bạn đến với VExchangeHome 🚀</h4>
        <p class="mb-4">Hãy tạo tài khoản mới để trải nghiệm những vùng đất mới.</p>

        <form id="formAuthentication" class="mb-3" asp-action="SignUp" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="FirstName" class="form-label">Họ và tên đệm</label>
                <input type="text" class="form-control" asp-for="FirstName" placeholder="Nguyễn Văn" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="LastName" class="form-label">Tên</label>
                <input type="text" class="form-control" asp-for="LastName" placeholder="Nguyễn Văn" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PhoneNumber" class="form-label">Số điện thoại</label>
                <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="000 0000 000" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="Email" placeholder="Enter your email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="Password">Mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           asp-for="Password"
                           class="form-control"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="ConfirmPassword">Xác nhận mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           class="form-control"
                           asp-for="ConfirmPassword"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Đăng ký</button>
        </form>

        <p class="text-center">
            <span>Bạn đã có tài khoản?</span>
            <a href="@Url.Action("SignIn", "Authorize")">
                <span>Đăng nhập</span>
            </a>
        </p>
    </div>
</div>

DoAnTotNghiep/Views/Authorize/SignUpCheckMail.cshtml
@model DoAnTotNghiep.ViewModels.RegisterCheckMailViewModel
@{
    ViewData["Title"] = "Đăng ký tài khoản";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Chào mừng bạn đến với VExchangeHome 🚀</h4>
        <p class="mb-4">Hãy tạo tài khoản mới để trải nghiệm những vùng đất mới.</p>

        <form id="formAuthentication" class="mb-3" asp-action="SignUpCheckMail" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="Email" placeholder="Enter your email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Tiếp tục</button>
        </form>

        <p class="text-center">
            <span>Bạn đã có tài khoản?</span>
            <a href="@Url.Action("SignIn", "Authorize")">
                <span>Đăng nhập</span>
            </a>
        </p>
    </div>
</div>

DoAnTotNghiep/Views/Authorize/SignUpInfo.cshtml
@model DoAnTotNghiep.ViewModels.RegisterInfoViewModel
@{
    ViewData["Title"] = "Đăng ký tài khoản";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Hoàn tất thông tin.</h4>
        <p class="mb-4">Điền các thông tin cá nhân của bạn.</p>

        <form id="formAuthentication" class="mb-3" asp-action="SignUpInfo" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="LastName" class="form-label">Họ & tên đệm</label>
                <input type="text" class="form-control" asp-for="LastName" placeholder="Nguyễn Văn" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="FirstName" class="form-label">Tên</label>
                <input type="text" class="form-control" asp-for="FirstName" placeholder="A" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Gender" class="form-label">Giới tính</label>
                <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender"></select>
            </div>
            <div class="mb-3">
                <label asp-for="BirthDay" class="form-label">Ngày sinh</label>
                <input class="form-control" asp-for="BirthDay" placeholder="dd/MM/yyyy" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="PhoneNumber" class="form-label">Số điện thoại</label>
                <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="000 0000 000" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Hoàn tất</button>
        </form>
    </div>
</div>

DoAnTotNghiep/Views/Authorize/SignUpPassword.cshtml
@model DoAnTotNghiep.ViewModels.RegisterPasswordViewModel
@{
    ViewData["Title"] = "Đăng ký tài khoản";
    Layout = "_LayoutLogin";
}


<!-- Register Card -->
<div class="card">
    <div class="card-body">
        <!-- Logo -->
        <div class="app-brand justify-content-center">
            <a href="@Url.Action("Index", "Home")" class="app-brand-link gap-2">
                <span class="app-brand-logo demo branch">
                    <img src="~/Image/logo.png" alt="logo" />
                </span>
                <span class="app-brand-text demo text-body fw-bolder">VExchangeHome</span>
            </a>
        </div>
        <!-- /Logo -->
        <h4 class="mb-2">Chào mừng bạn đến với VExchangeHome 🚀</h4>
        <p class="mb-4">Hãy tạo tài khoản mới để trải nghiệm những vùng đất mới.</p>

        <form id="formAuthentication" class="mb-3" asp-action="SignUpPassword" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger">
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    @ViewBag.Message
                }
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input type="text" class="form-control" asp-for="Email" placeholder="Enter your email" readonly/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="Password">Mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           asp-for="Password"
                           class="form-control"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3 form-password-toggle">
                <label class="form-label" asp-for="ConfirmPassword">Xác nhận mật khẩu</label>
                <div class="input-group input-group-merge">
                    <input type="password"
                           class="form-control"
                           asp-for="ConfirmPassword"
                           placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                           aria-describedby="password" />
                </div>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary d-grid w-100">Tiếp tục</button>
        </form>

        <p class="text-center">
            <span>Bạn đã có tài khoản?</span>
            <a href="@Url.Action("SignIn", "Authorize")">
                <span>Đăng nhập</span>
            </a>
        </p>
    </div>
</div>