DoAnTotNghiep/ViewModels/RatingViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DoAnTotNghiep.Entity;

namespace DoAnTotNghiep.ViewModels
{
    public class CreateRatingViewModel
    {
        public int? RatingHouse { get; set; }
        [Required(ErrorMessage = "Hãy đánh giá người dùng")]
        public int RatingUser { get; set; }
        [Required(ErrorMessage = "Hãy chọn yêu cầu đánh giá")]
        public int IdRequest { get; set; }
        [Required(ErrorMessage = "Hãy điền nội dung")]
        [MaxLength(1000, ErrorMessage = "Nội dung tối đa 500 ký tự")]
        public string Content { get; set; } = string.Empty;
    }

    public class EditRatingViewModel: CreateRatingViewModel
    {
        public EditRatingViewModel(){}
        public EditRatingViewModel(FeedBack feed)
        {
            this.Id = feed.Id;
            this.RatingHouse = feed.Rating;
            this.RatingUser = feed.RatingUser;
            this.Content = feed.Content;
            this.IdRequest = feed.IdRequest;
        }
        public EditRatingViewModel(FeedBackOfCircle feed)
        {
            this.Id = feed.Id;
            this.RatingHouse = feed.RateHouse;
            this.RatingUser = feed.RateUser;
            this.Content = feed.Content;
            this.IdRequest = feed.IdCircle;
        }
        [Required]
        public int Id { get; set; }
    }

    public class DetailRatingViewModel
    {
        public DetailRatingViewModel()
        {

        }
        public DetailRatingViewModel(FeedBack feedBack)
        {
            this.CreatedDate = feedBack.CreatedDate;
            this.UpdatedDate = feedBack.UpdatedDate;
            this.Content = feedBack.Content;
            this.Rating = feedBack.Rating;
            this.RatingUser = feedBack.RatingUser;
            this.Id = feedBack.Id;
            if(feedBack.Users != null)
            {
                this.UserName = feedBack.Users.FirstName + " " + feedBack.Users.LastName;
            }
            this.IdRequest = feedBack.IdRequest;
        }

        public DetailRatingViewModel(FeedBackOfCircle feedBack, int IdUser)
        {
            this.CreatedDate = feedBack.CreatedDate;
            this.UpdatedDate = feedBack.UpdatedDate;
            this.Content = feedBack.Content;
            this.Rating = feedBack.RateHouse;
            this.RatingUser = feedBack.RateUser;
            this.Id = feedBack.Id;
            if (feedBack.UserRating != null)
            {
                this.UserName = feedBack.UserRating.FirstName + " " + feedBack.UserRating.LastName;
            }
            this.IsOwner = IdUser == feedBack.IdUserRating;
            this.IdRequest = feedBack.IdCircle;
        }

        public DateTime UpdatedDate { get; set; } = DateTime.Now;
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public string Content { get; set; } = string.Empty;
        public int Rating { get; set; } = 0;
        public int RatingUser { get; set; } = 0;
        public string UserName { get; set; } = string.Empty;
        public int Id { get; set; } = 0;
        public int IdRequest { get; set; } = 0;
        public bool IsOwner { get; set; } = false;
    }

    public class DetailRatingWithUser
    {
        public DetailRatingWithUser() { }

        public DetailRatingWithUser(FeedBack feedBack, byte[] salt, string host) { 
            this.FeedBack = new DetailRatingViewModel(feedBack);
            if(feedBack.Users!= null)
            {
                this.User = new UserInfo(feedBack.Users, salt, host);
            }
        }
        public UserInfo User { get; set; } = new UserInfo();
        public DetailRatingViewModel FeedBack { get; set; } = new DetailRatingViewModel();
    }
    public class ListRating
    {
        public FrameRating OverView { get; set; } = new FrameRating();
        public List<DetailRatingWithUser> Rating { get; set; } = new List<DetailRatingWithUser>();
    }

    public class FrameRating
    {
        public int OneStar { get; set; } = 0;
        public int TwoStar { get; set; } = 0;
        public int ThreeStar { get; set; } = 0;
        public int FourStar { get; set; } = 0;
        public int FiveStar { get; set; } = 0;
        public int Total() => OneStar + TwoStar + ThreeStar + FourStar + FiveStar;
        public double Rating() => (double) (OneStar + TwoStar*2 + ThreeStar*3 + FourStar*4 + FiveStar*5)/Total();
    }
}

DoAnTotNghiep/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnTotNghiep.Data;
using DoAnTotNghiep.Entity;
using DoAnTotNghiep.ViewModels;
using DoAnTotNghiep.Modules;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Security.Claims;
using DoAnTotNghiep.Enum;
using NuGet.Protocol;
using System.Configuration;
using System.IdentityModel.Tokens.Jwt;
using NuGet.Common;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using static System.Net.WebRequestMethods;
using System.Composition;
using Microsoft.Extensions.Hosting;
using static System.ComponentModel.BackgroundWorker;
using System.ComponentModel;
using System.Xml;
using Azure.Core;
using DoAnTotNghiep.Hubs;
using Microsoft.AspNetCore.SignalR;
using DoAnTotNghiep.Service;
using Org.BouncyCastle.Asn1.Ocsp;

namespace DoAnTotNghiep.Controllers
{
    [Authorize(Roles = Role.Member)]
    public class RatingController: BaseController
    {
        private readonly DoAnTotNghiepContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHubContext<ChatHub> _signalContext;
        private readonly IFeedBackService _feedBackService;
        private readonly IRequestService _requestService;
        private readonly IFileService _fileService;
        private readonly IHouseService _houseService;
        private readonly IUserService _userService;
        private readonly INotificationService _notificationService;
        private readonly ITransactionService _transactionService;

        public RatingController(
                                DoAnTotNghiepContext context, 
                                IConfiguration configuration, 
                                IHostEnvironment environment, 
                                IHubContext<ChatHub> signalContext,
                                IFeedBackService feedBackService,
                                IRequestService requestService,
                                IFileService fileService,
                                IHouseService houseService,
                                IUserService userService,
                                INotificationService notificationService,
                                ITransactionService transactionService) : base(environment)
        {
            _context = context;
            _configuration = configuration;
            _signalContext = signalContext;
            _feedBackService = feedBackService;
            _requestService = requestService;
            _fileService = fileService;
            _houseService = houseService;
            _userService = userService;
            _notificationService = notificationService;
            _transactionService = transactionService;
    }

        [HttpGet("/Rating/Form")]
        public IActionResult FormCreateRating(int IdRequest, int? IdRating)
        {
            var request = this._requestService.GetRequestById(IdRequest);
            if (request == null) return NotFound();
            int idUser = this.GetIdUser();
            bool isCan = ((request.IdUser == idUser) || (request.IdUser != idUser) && request.Type == 2);

            ViewData["isCan"] = isCan ? "true" : "false";
            if(IdRating != null)
            {
                var rating = this._feedBackService.GetRatingById(IdRating.Value);
                if(rating != null)
                {
                    EditRatingViewModel editRating = new EditRatingViewModel(rating);
                    return PartialView("~/Views/Rating/_EditFormRating.cshtml", editRating);
                }
            }
            return PartialView("~/Views/Rating/_FormRating.cshtml", IdRequest);
        }

        private async Task<IActionResult> CreateAsync(CreateRatingViewModel feedBack)
        {
            if (ModelState.IsValid)
            {
                int IdUser = this.GetIdUser();
                var request = this._requestService.GetRequestByFeedBack(feedBack.IdRequest, IdUser);
                if(request != null)
                {
                    request.IncludeAll(this._context);
                    if(request.Houses != null)
                    {
                        request.Houses.IncludeAll(this._context);
                        if(request.Houses.Users != null)
                        {
                            if (request.Users != null)
                            {
                                string host = this.GetWebsitePath();
                                if (request.IdUser == IdUser)
                                {
                                    using (var transaction = this._context.Database.BeginTransaction())
                                    {
                                        try
                                        {
                                            FeedBack model = new FeedBack();
                                            model.Create(feedBack, IdUser, request.Houses.Users.Id, request.Houses.Id);
                                            this._feedBackService.Save(model);

                                            List<int> intsHouse = this._houseService.CalRating(request.Houses.Id);
                                            request.Houses.Rating = Math.Ceiling((double)intsHouse.First()/ intsHouse.Last());
                                            request.Houses.NumberOfRating += 1;
                                            this._houseService.UpdateHouse(request.Houses);

                                            List<int> ints = this._userService.CalRate(request.Houses.Users.Id);
                                            request.Houses.Users.UserRating = Math.Ceiling((double)ints.First() / ints.Last());
                                            request.Houses.Users.NumberUserRating += 1;
                                            this._userService.UpdateUser(request.Houses.Users);

                                            if(request.IdSwapHouse == null || request.IdSwapHouse != null && request.FeedBacks != null && request.FeedBacks.Count() > 1)
                                            {
                                                request.Status = (int)StatusRequest.ENDED;
                                                request.UpdatedDate = DateTime.Now;
                                                this._requestService.UpdateRequest(request);
                                            }
                                            //tăng điểm người dùng
                                            request.Users.BonusPoint += (int)Math.Floor(Math.Abs(request.Point) * 0.1);
                                            this._userService.UpdateUser(request.Users);

                                            //gửi thông báo
                                            Notification notification = new Notification().FeedBackNotification(request, request.Houses.Users.Id);
                                            this._notificationService.SaveNotification(notification);
                                            transaction.Commit();

                                            await new ChatHub(this._signalContext).SendNotification(
                                                group: Crypto.EncodeKey(notification.IdUser.ToString(),
                                                Crypto.Salt(this._configuration)),
                                                target: TargetSignalR.Notification(),
                                                model: new NotificationViewModel(notification, host));
                                            return Json(new
                                            {
                                                Status = 200,
                                                Message = "ok"
                                            });
                                        }
                                        catch (Exception ex)
                                        {
                                            Console.WriteLine(ex);
                                            transaction.Rollback();
                                        }
                                    }
                                    return BadRequest(new
                                    {
                                        Status = 500,
                                        Message = "Không lưu được"
                                    });
                                }
                                else if(request.Houses.Users.Id == IdUser)
                                {
                                    using (var transaction = this._context.Database.BeginTransaction())
                                    {
                                        try
                                        {
                                            FeedBack model = new FeedBack();
                                            model.Create(feedBack, request.Houses.Users.Id, request.Users.Id, request.SwapHouses == null ? null : request.SwapHouses.Id);
                                            this._feedBackService.Save(model);

                                            if (request.SwapHouses != null)
                                            {
                                                List<int> intsHouse = this._houseService.CalRating(request.SwapHouses.Id);
                                                request.SwapHouses.Rating = Math.Ceiling((double)intsHouse.First() / intsHouse.Last());
                                                request.Houses.Users.NumberUserRating += 1;
                                                this._houseService.UpdateHouse(request.SwapHouses);

DoAnTotNghiep/Views/Rating/_Comment.cshtml
@model DetailRatingWithUser
@using DoAnTotNghiep.Enum;

<div class="comment">
    <div class="comment-head">
        @if (!string.IsNullOrEmpty(Model.User.UrlImage))
        {
            <div class="avt"><img src="@Model.User.UrlImage" alt="avt-user" /></div>
        }
        else{
            <div class="avt"><img src="~/Image/user.svg" alt="avt-user" /></div>
        }
        <div class="info">
            <h5>
                <span class="name"> @Model.User.LastName @Model.User.FirstName</span>
                <span class="rating">
                    <span><span>Đánh giá chất lượng nhà: @Model.FeedBack.Rating</span><i class="fa-solid fa-star"></i></span>
                    <span><span>Đánh giá người dùng: @Model.FeedBack.RatingUser</span><i class="fa-solid fa-star"></i></span>
                </span>
            </h5>
            <div class="date"><span>@Model.FeedBack.UpdatedDate.ToString("dd/MM/yyyy")</span></div>
        </div>
    </div>
    <div class="comment-content">
        @Model.FeedBack.Content
    </div>
</div>

DoAnTotNghiep/Views/Rating/_EditFormRating.cshtml
@model EditRatingViewModel


<div class="modal fade" id="ratingModal" tabindex="-1" aria-labelledby="ratingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="text-danger fw-semibold branch">Đánh giá trải nghiệm</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="@Url.Action("Update", "Rating")" method="post" id="form-create">
                    @if (!(string.IsNullOrEmpty(ViewData["isCan"] as string)) && ViewData["isCan"] == "true")
                    {
                        <div class="mb-3 item-house">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="label">
                                    <i class="fa-solid fa-house"></i>
                                    <span>Đánh giá căn hộ</span>
                                </div>
                                <div class="star-select">
                                    <i class="fa-solid fa-star" onclick="addStar('item-house', 1)"></i>
                                    <div class="star-select">
                                        <i class="fa-solid fa-star" onclick="addStar('item-house', 2)"></i>
                                        <div class="star-select">
                                            <i class="fa-solid fa-star" onclick="addStar('item-house', 3)"></i>
                                            <div class="star-select">
                                                <i class="fa-solid fa-star" onclick="addStar('item-house', 4)"></i>
                                                <div class="star-select">
                                                    <i class="fa-solid fa-star" onclick="addStar('item-house', 5)"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="mb-3 user">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="label">
                                <i class="fa-solid fa-user"></i>
                                <span>Đánh giá người dùng</span>
                            </div>
                            <div class="star-select">
                                <i class="fa-solid fa-star" onclick="addStar('user', 1)"></i>
                                <div class="star-select">
                                    <i class="fa-solid fa-star" onclick="addStar('user', 2)"></i>
                                    <div class="star-select">
                                        <i class="fa-solid fa-star" onclick="addStar('user', 3)"></i>
                                        <div class="star-select">
                                            <i class="fa-solid fa-star" onclick="addStar('user', 4)"></i>
                                            <div class="star-select">
                                                <i class="fa-solid fa-star" onclick="addStar('user', 5)"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-danger" id="user-valid"></div>
                    </div>
                    <div class="mb-3">
                        <label for="contentRating">Cảm nghĩ của bạn về chuyến đi</label>
                        <textarea class="form-control" id="contentRating" name="contentRating" rows="5" onchange="checkRatingValid()">@(Model.Content)</textarea>
                        <div class="text-danger" id="contentRating-valid"></div>
                    </div>
                </form>
                <button type="button" class="btn btn-primary" onclick="editRating()">Đánh giá</button>
            </div>
        </div>
    </div>
</div>
<button class="d-none" type="button" id="ratingModalClick" data-bs-toggle="modal" data-bs-target="#ratingModal"></button>



<script src="~/js/Rating/edit.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#ratingModalClick").click();
    var ratingData = {
        ratingUser: @(Model.RatingUser),
        idRequest: @(Model.IdRequest),
        content: '@Html.Raw(Model.Content)',
        ratingHouse: @Model.RatingHouse,
        id: @Model.Id
    }
</script>
@if(Model.RatingHouse != null){
    <script type="text/javascript">
        addStar("item-house", @Model.RatingHouse.Value)
    </script>
}

<script type="text/javascript">
    addStar("user", @(Model.RatingUser));
</script>

DoAnTotNghiep/Views/Rating/_FormRating.cshtml
@model int
@using DoAnTotNghiep.Enum;

<div class="modal fade" id="ratingModal" tabindex="-1" aria-labelledby="ratingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="text-danger fw-semibold branch">Đánh giá trải nghiệm</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="@Url.Action("Create", "Rating")" method="post" id="form-create">
                    @if (!(string.IsNullOrEmpty(ViewData["isCan"] as string)) && (ViewData["isCan"] as string) == "true")
                    {
                        <div class="mb-3 item-house">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="label">
                                    <i class="fa-solid fa-house"></i>
                                    <span>Đánh giá căn hộ</span>
                                </div>
                                <div class="star-select">
                                    <i class="fa-solid fa-star" onclick="addStar('item-house', 1)"></i>
                                    <div class="star-select">
                                        <i class="fa-solid fa-star" onclick="addStar('item-house', 2)"></i>
                                        <div class="star-select">
                                            <i class="fa-solid fa-star" onclick="addStar('item-house', 3)"></i>
                                            <div class="star-select">
                                                <i class="fa-solid fa-star" onclick="addStar('item-house', 4)"></i>
                                                <div class="star-select">
                                                    <i class="fa-solid fa-star" onclick="addStar('item-house', 5)"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="mb-3 user">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="label">
                                <i class="fa-solid fa-user"></i>
                                <span>Đánh giá người dùng</span>
                            </div>
                            <div class="star-select">
                                <i class="fa-solid fa-star" onclick="addStar('user', 1)"></i>
                                <div class="star-select">
                                    <i class="fa-solid fa-star" onclick="addStar('user', 2)"></i>
                                    <div class="star-select">
                                        <i class="fa-solid fa-star" onclick="addStar('user', 3)"></i>
                                        <div class="star-select">
                                            <i class="fa-solid fa-star" onclick="addStar('user', 4)"></i>
                                            <div class="star-select">
                                                <i class="fa-solid fa-star" onclick="addStar('user', 5)"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-danger" id="user-valid"></div>
                    </div>
                    <div class="mb-3">
                        <label for="contentRating">Cảm nghĩ của bạn về chuyến đi</label>
                        <textarea class="form-control" id="contentRating" name="contentRating" rows="5" onchange="checkRatingValid()"></textarea>
                        <div class="text-danger" id="contentRating-valid"></div>
                    </div>
                </form>
                <button type="button" class="btn btn-primary" onclick="createRating()">Đánh giá</button>
            </div>
        </div>
    </div>
</div>
<button class="d-none" type="button" id="ratingModalClick" data-bs-toggle="modal" data-bs-target="#ratingModal"></button>

<script type="text/javascript">
    $("#ratingModalClick").click();
    var ratingData = {
        ratingHouse: null,
        idRequest: @(Model),
        content: null,
        ratingUser: null
    }
</script>
<script src="~/js/Rating/create.js" type="text/javascript"></script>

DoAnTotNghiep/Views/Rating/_ListRating.cshtml
@model ListRating
@using DoAnTotNghiep.Enum;
@{
    double rating = Math.Ceiling(Model.OverView.Rating());
}
    <span class="heading">Người dùng đánh giá</span>
    <span class="fa fa-star @if(rating >= 1){@Html.Raw("checked")}"></span>
    <span class="fa fa-star @if(rating >= 2){@Html.Raw("checked")}"></span>
    <span class="fa fa-star @if(rating >= 3){@Html.Raw("checked")}"></span>
    <span class="fa fa-star @if(rating >= 4){@Html.Raw("checked")}"></span>
    <span class="fa fa-star @if(rating >= 5){@Html.Raw("checked")}"></span>
    <p>Dựa trên @Model.OverView.Total() đánh giá từ người dùng.</p>
    <hr style="border:3px solid #f1f1f1">
    <div class="rate-overview">
        <div class="line-star">
            <div class="side">
                <div>5 Sao</div>
            </div>
            <div class="middle">
                <div class="bar-container">
                <div class="bar-5" style="width: @(((double) Model.OverView.FiveStar / (double) Model.OverView.Total()) * 100)%"></div>
                </div>
            </div>
            <div class="side right">
                <div>@Model.OverView.FiveStar</div>
            </div>
        </div>

        <div class="line-star">
            <div class="side">
                <div>4 Sao</div>
            </div>
            <div class="middle">
                <div class="bar-container">
                <div class="bar-4" style="width: @Math.Ceiling(((double) Model.OverView.FourStar / (double) Model.OverView.Total()) * 100)%"></div>
                </div>
            </div>
            <div class="side right">
                <div>@Model.OverView.FourStar</div>
            </div>
        </div>

        <div class="line-star">
            <div class="side">
                <div>3 Sao</div>
            </div>
            <div class="middle">
                <div class="bar-container">
                <div class="bar-3" style="width: @Math.Ceiling(((double) Model.OverView.ThreeStar /(double) Model.OverView.Total()) * 100)%"></div>
                </div>
            </div>
            <div class="side right">
                <div>@Model.OverView.ThreeStar</div>
            </div>
        </div>

        <div class="line-star">
            <div class="side">
                <div>2 Sao</div>
            </div>
            <div class="middle">
                <div class="bar-container">
                <div class="bar-2" style="width: @Math.Ceiling(((double)Model.OverView.TwoStar / (double) Model.OverView.Total()) * 100)%"></div>
                </div>
            </div>
            <div class="side right">
                <div>@Model.OverView.TwoStar</div>
            </div>
        </div>

        <div class="line-star">
            <div class="side">
                <div>1 Sao</div>
            </div>
            <div class="middle">
                <div class="bar-container">
                <div class="bar-1" style="width: @Math.Ceiling(((double) Model.OverView.OneStar/(double)Model.OverView.Total()) * 100)%"></div>
            </div>
            </div>
            <div class="side right">
                <div>@Model.OverView.OneStar</div>
            </div>
        </div>
    </div>

    <div class="frame-list-comment">
        @foreach (var item in Model.Rating)
        {
            @(await Html.PartialAsync("~/Views/Rating/_Comment.cshtml", item))
            @*

            <div class="comment">
                <div class="comment-head">
                    @if (!string.IsNullOrEmpty(item.User.UrlImage))
                    {
                        <div class="avt"><img src="@item.User.UrlImage" alt="avt-user" /></div>
                    }
                    else{
                        <div class="avt"><img src="~/Image/user.svg" alt="avt-user" /></div>
                    }
                    <div class="info">
                        <h5><span class="name">@item.User.FirstName @item.User.LastName</span>
                            <span class="rating">
                                <span><span>Đánh giá chất lượng nhà: @item.FeedBack.Rating</span><i class="fa-solid fa-star"></i></span>
                                <span><span>Đánh giá người dùng: @item.FeedBack.RatingUser</span><i class="fa-solid fa-star"></i></span>
                            </span>
                        </h5>
                        <div class="date"><span>@item.FeedBack.UpdatedDate.ToString("dd/MM/yyyy")</span></div>
                    </div>
                </div>
                <div class="comment-content">
                    @item.FeedBack.Content
                </div>
            </div>
    *@
        }
    </div>