DoAnTotNghiep/ViewModels/ReportViewModel.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoAnTotNghiep.ViewModels
{
    public class ReportViewModel
    {
        public int? IdHouse { get; set; } = 0;
        public string? UserAccess { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public List<ImageBase> Images { get; set; } = new List<ImageBase>();
    }

    public class MobileReportViewModel
    {
        public int? IdHouse { get; set; } = 0;
        public string? UserAccess { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public IFormFileCollection? Files { get; set; }
    }

    public class CreateReportViewModel
    {
        public int? IdHouse { get; set; } = 0;
        public int? IdUser { get; set; } = 0;
        public string Content { get; set; } = string.Empty;
        public List<ImageBase> Images { get; set; } = new List<ImageBase>();
        public IFormFileCollection? Files { get; set; } 
    }

    public class DetailReportViewModel
    {
        public string Content { get; set; } = string.Empty;
        public List<ImageBase> Images { get; set; } = new List<ImageBase>();
        public UserMessageViewModel User { get; set; } = new UserMessageViewModel();
    }

    public class Report
    {
        public DetailHouseViewModel House { get; set; } = new DetailHouseViewModel();
        public List<DetailReportViewModel> Details { get; set; } = new List<DetailReportViewModel>();
        //thêm cái response ở đây
    }

    public class ReportItem
    {
        public DetailHouseViewModel House { get; set; } = new DetailHouseViewModel();
        public int NumberReport { get; set; } = 0;
    }
}

DoAnTotNghiep/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnTotNghiep.Data;
using DoAnTotNghiep.Entity;
using Microsoft.AspNetCore.Authorization;
using DoAnTotNghiep.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.Extensions.Hosting;
using System.Buffers.Text;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Net;
using DoAnTotNghiep.Enum;
using Microsoft.AspNetCore.Routing;
using DoAnTotNghiep.Modules;
using NuGet.Packaging;
using System.Text;
using Microsoft.EntityFrameworkCore.Internal;
using DoAnTotNghiep.Service;
using System.Net.WebSockets;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace DoAnTotNghiep.Controllers
{
    [Authorize(Roles = Enum.Role.Member)]
    public class HousesController : BaseController
    {
        //xong
        private readonly DoAnTotNghiepContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHouseService _houseService;
        private readonly IFeedBackService _feedBackService;
        private readonly IFileService _fileService;
        private readonly IRuleService _ruleService;
        private readonly IUtilitiesService _utilitiesService;
        public HousesController(DoAnTotNghiepContext context,
                                IHostEnvironment environment,
                                IConfiguration configuration,
                                IHouseService houseService,
                                IFeedBackService feedBackService,
                                IFileService fileService,
                                IRuleService ruleService,
                                IUtilitiesService utilitiesService) : base(environment)
        {
            _context = context;
            _configuration = configuration;
            _houseService = houseService;
            _feedBackService = feedBackService;
            _fileService = fileService;
            _ruleService = ruleService;
            _utilitiesService = utilitiesService;
        }

        private async Task<DetailHouseViewModel> CreateHouse(CreateHouse data)
        {
            if (ModelState.IsValid)
            {
                int IdUser = this.GetIdUser();
                string? key = this._configuration.GetConnectionString(BingMaps.Key);
                if (!string.IsNullOrEmpty(key) && (data.Lat == 0 || data.Lng == 0))
                {
                    string query = data.Location + ", " + data.WardName + ", " + data.DistrictName + ", " + data.CityName;
                    List<double> doubles = await RequestAPI.GetLocation(this.Request.Scheme, key, query);
                    data.Lat = doubles[0];
                    data.Lng = doubles[1];
                }
                House house = new House().CreateHouse(data, IdUser, (int)StatusHouse.VALID);
                using (var transaction = await this._context.Database.BeginTransactionAsync())
                {
                    try
                    {
                        this._houseService.SaveHouse(house);
                        this._ruleService.AddRuleForHouse(house, data.Rules);
                        this._utilitiesService.AddUtilitiesForHouse(house, data.Utilities);

                        house.IncludeAll(this._context);

                        //thêm hình
                        List<Entity.File> files = new List<Entity.File>();

                        if (data.Files == null)
                        {
                            files.AddRange(this._fileService.SaveRangeFile(this._fileService.AddFile(data.Images, this.environment.ContentRootPath)));
                        }
                        else
                        {
                            files.AddRange(this._fileService.SaveRangeFile(this._fileService.AddFile(data.Files, this.environment.ContentRootPath)));
                        }
                        this._fileService.SaveRangeFileOfHouse(house, files);
                        transaction.Commit();

                        byte[] salt = Crypto.Salt(this._configuration);

                        DetailHouseViewModel detailHouseViewModel = new DetailHouseViewModel(house, salt);
                        detailHouseViewModel.Rules = data.Rules;
                        detailHouseViewModel.Utilities = data.Utilities;
                        detailHouseViewModel.CityName = house.Citys?.Name;
                        detailHouseViewModel.DistrictName = house.Districts?.Name;
                        detailHouseViewModel.WardName = house.Wards?.Name;

                        string host = this.GetWebsitePath();
                        List<ImageBase> images = new List<ImageBase>();
                        foreach (var item in files) images.Add(new ImageBase(item, host));
                        detailHouseViewModel.Images.AddRange(images);
                        return detailHouseViewModel;
                    }
                    catch (Exception ex)
                    {
                        FileSystem.WriteExceptionFile(ex.ToString(), "SaveHouse_" + IdUser);
                        transaction.Rollback();
                        return new DetailHouseViewModel() { Id = 0 };
                    }
                }
            }
            return new DetailHouseViewModel() { Id = -1 };
        }
        [HttpPost("House/Create")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create([FromBody] CreateHouseViewModel data)
        {
            DetailHouseViewModel returnCode = await this.CreateHouse(new CreateHouse(null, data));
            switch (returnCode.Id)
            {
                case -1:
                    return Json(new
                    {
                        Status = 400,
                        Message = ModelErrors()
                    });
                case 0:
                    return Json(new
                    {
                        Status = HttpStatusCode.InternalServerError,
                        Message = "Ứng dụng tạm thời bảo trì"
                    });
            }
            return Json(new
            {
                Status = 200,
                Message = "Đã khởi tạo thành công!",
                Data = returnCode
            });
        }
        [HttpPost("/api/House/Create")]
        public async Task<IActionResult> ApiCreate(MobileCreateHouseViewModel data)
        {
            DetailHouseViewModel returnCode = await this.CreateHouse(new CreateHouse(data, null));
            switch (returnCode.Id)
            {
                case -1:
                    return BadRequest(new
                    {
                        Status = 400,
                        Message = this.ModelErrors()
                    });
                case 0:
                    return BadRequest(new
                    {
                        Status = 500,
                        Message = "Ứng dụng tạm thời bảo trì"
                    });
            }
            return Json(new
            {
                Status = 200,
                Message = "Đã khởi tạo thành công",
                Data = new { }
            });
        }

        private async Task<IActionResult> EditHouse(EditHouse data)
        {
            if (ModelState.IsValid)
            {
                int IdUser = this.GetIdUser();
                var model = this._houseService.GetHouseByIdWithUser(data.Id, IdUser);
                if (model == null)
                {
                    return BadRequest(new
                    {
                        Status = 404,
                        Message = "Không tìm thấy nhà"
                    });
                }
                string? key = this._configuration.GetConnectionString(BingMaps.Key);
                if (!string.IsNullOrEmpty(key) && (data.Lat == 0 || data.Lng == 0))
                {
                    string query = data.Location + ", " + data.WardName + ", " + data.DistrictName + ", " + data.CityName;
                    List<double> doubles = await RequestAPI.GetLocation(this.Request.Scheme, key, query);
                    data.Lat = doubles[0];
                    data.Lng = doubles[1];
                }
                using (var transaction = await this._context.Database.BeginTransactionAsync())
                {
                    try
                    {
                        model.IncludeAll(this._context);
                        model.EditHouse(data);
                        this._houseService.UpdateHouse(model);
                        this._ruleService.UpdateRuleForHouse(model, data.Rules);
                        this._utilitiesService.UpdateUtilitiesForHouse(model, data.Utilities);

                        List<Entity.File> files = new List<Entity.File>();
                        if (data.Files == null)
                        {
                            files.AddRange(this._fileService.SaveRangeFile(this._fileService.UpdateFileHouse(model, data.Images, this.environment.ContentRootPath)));
                        }
                        else
                        {
                            files.AddRange(this._fileService.SaveRangeFile(this._fileService.UpdateFileHouse(model, data.Files, data.IdRemove, this.environment.ContentRootPath)));
                        }
                        this._fileService.SaveRangeFileOfHouse(model, files);

                        transaction.Commit();

                        byte[] salt = Crypto.Salt(this._configuration);
                        DetailHouseViewModel detailHouseViewModel = new DetailHouseViewModel(model, salt);
                        detailHouseViewModel.Rules = data.Rules;
                        detailHouseViewModel.Utilities = data.Utilities;

DoAnTotNghiep/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnTotNghiep.Data;
using DoAnTotNghiep.Entity;
using DoAnTotNghiep.Service;
using Microsoft.AspNetCore.Authorization;
using DoAnTotNghiep.Enum;
using DoAnTotNghiep.Modules;
using DoAnTotNghiep.ViewModels;
using System.Composition.Convention;

namespace DoAnTotNghiep.Controllers
{
    [Authorize(Roles = Role.Admin)]
    public class UsersController : BaseController
    {
        private readonly DoAnTotNghiepContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHouseService _houseService;
        private readonly IUserService _userService;
        private readonly IFileService _fileService;
        private readonly IRequestService _requestService;
        private readonly IFeedBackService _feedBackService;
        public UsersController(DoAnTotNghiepContext context,
                                IRequestService requestService,
                                IFileService fileService,
                                IHouseService houseService,
                                IUserService userService,
                                IConfiguration configuration,
                                IHostEnvironment environment,
                                IFeedBackService feedBackService) : base(environment)
        {
            _context = context;
            _houseService = houseService;
            _userService = userService;
            _fileService = fileService;
            _requestService = requestService;
            _configuration = configuration;
            _feedBackService = feedBackService;
        }
        [HttpGet("/User/GetNumberSwap")]
        public IActionResult GetNumberSwap(int userId)
        {
            return Json(new
            {
                Status = 200,
                Data = this._userService.NumberSwap(userId)
            });
        }
        [HttpPost("/User/BanUser")]
        public IActionResult Ban([FromBody] int idUser)
        {
            var user = this._userService.GetById(idUser);
            if(user == null)
            {
                return BadRequest(new
                {
                    Status = 400,
                    Message = "Không tìm thấy người dùng"
                });
            }
            user.IsBan = true;
            this._userService.UpdateUser(user);
            return Json(new {
                Status = 200,
                Message = "ok"
            });
        }
        [HttpGet("/User/Details")]
        public IActionResult Details(int idUser)
        {
            var user = this.Profile(idUser);
            if (user == null) return NotFound();
            int IdUser = this.GetIdUser();
            if (IdUser != 0)
            {
                this.SetViewData(new DoAnTotNghiepContext(this._context.GetConfig()), IdUser, Crypto.Salt(this._configuration));
            }
            return View("~/Views/Users/_Details.cshtml", user);
        }
        [HttpGet("/Admin/OverViewProfile")]
        public IActionResult OverViewProfile(string? UserAccess)
        {
            int IdAnotherUser = 0;
            if (string.IsNullOrEmpty(UserAccess) || !int.TryParse(Crypto.DecodeKey(UserAccess, Crypto.Salt(this._configuration)), out IdAnotherUser))
            {
                return NotFound();
            }
            var user = this.Profile(IdAnotherUser);
            if (user == null) return NotFound();
            int IdUser = this.GetIdUser();
            if (IdUser != 0)
            {
                this.SetViewData(new DoAnTotNghiepContext(this._context.GetConfig()), IdUser, Crypto.Salt(this._configuration));
            }
            return View("~/Views/Users/_Details.cshtml", user);
        }
        public UserProfile? Profile(int idUser)
        {
            var user = this._userService.GetById(idUser);
            if (user == null) return null;
            byte[] salt = Crypto.Salt(this._configuration);
            string host = this.GetWebsitePath();
            UserInfo.GetEntityRelated(user, this._context);

            return new UserProfile(
                                new UserInfo(user, salt, host),
                                this._houseService.GetListDetailHouseWithOneImage(
                                this._houseService.GetListHouseByUser(idUser),
                                this._fileService, host, salt),
                                this._feedBackService.GetRatingById(idUser, host, salt));
        }
    }
}

DoAnTotNghiep/Views/Users/_Details.cshtml
@model UserProfile
@using DoAnTotNghiep.Enum;
@{
    ViewData["Title"] = "Thông tin người dùng";
}
@if(Model != null){
    <div class="profile">
        <div class="avt">
            @if (string.IsNullOrEmpty(Model.User.UrlImage))
            {
                <img src="/Image/user.svg" alt="avatar của Hiếu" class="img-avt" />
            }
            else
            {
                <img src="@Model.User.UrlImage" alt="avatar của Hiếu" class="img-avt" />
            }
        </div>
        <div class="info">
            <div class="name"><strong>@Model.User.LastName @Model.User.FirstName</strong></div>
            <div class="rate">
                <div class="frame-start">
                    <span class="fa fa-star @if(Model.User.UserRating >= 1){@Html.Raw("checked")}"></span>
                    <span class="fa fa-star @if(Model.User.UserRating >= 2){@Html.Raw("checked")}"></span>
                    <span class="fa fa-star @if(Model.User.UserRating >= 3){@Html.Raw("checked")}"></span>
                    <span class="fa fa-star @if(Model.User.UserRating >= 4){@Html.Raw("checked")}"></span>
                    <span class="fa fa-star @if(Model.User.UserRating >= 5){@Html.Raw("checked")}"></span>
                </div>
                <div class="number-rate"><strong>@Model.User.NumberRating</strong> người đánh giá</div>
            </div>
            <div class="swap">
                <div class="label"><span>Số lượt trao đổi: </span><strong>@Model.User.NumberSwap</strong></div>
                <div class="label"><span>Email: </span><strong>@Model.User.Email</strong></div>
                <div class="label"><span>Số điện thoại: </span><strong>@Model.User.PhoneNumber</strong></div>
                <div class="label"><span>Ngày sinh: </span><strong>@Model.User.BirthDay.Value.ToString("dd/MM/yyyy")</strong></div>
                <div class="label"><span>Giới tính: </span><strong>@((!Model.User.Gender.HasValue || Model.User.Gender.Value == true) ? "Nam" : "Nữ")</strong></div>
            </div>
        </div>
    </div>
    <div class="list-house">
        <h2 class="title">Danh sách nhà của người dùng</h2>
        <div class="list">
            @foreach(var item in Model.Houses)
            {
                <div class="house-result">
                    <div class="house-card">
                        <img src="@item.Images.FirstOrDefault()?.Data" alt="Mike" style="width:100%">
                        <div class="house-img-container">
                            <h2>@item.Name</h2>
                            <p class="attribute">
                                <i class="fa-solid fa-map-location-dot"></i><span>
                                    @item.Location, @item.WardName, @item.DistrictName, @item.CityName
                                </span>
                            </p>
                            <div class="list-attribute">
                                <p class="attribute"><span>@item.Rating (@item.NumberRating)</span><i class="fa-solid fa-star"></i></p>
                                <p class="attribute"><i class="fa-solid fa-users"></i><span>@item.People</span></p>
                                <p class="attribute"><i class="fa-solid fa-bed"></i><span>@item.BedRoom</span></p>
                            </div>
                            <p>
                                <button class="item-button">
                                    <span>@item.Price @HouseEnum.UnitPrice</span>
                                </button>
                            </p>
                        </div>
                        <a target="_blank" href='@Url.Action("Details", "Houses", new {Id = item.Id})' class="finding">
                            <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="list-review">
        <h2 class="title">Nhận xét từ người dùng</h2>
        @foreach(var item in Model.Rating)
        {
            @(await Html.PartialAsync("~/Views/Rating/_Comment.cshtml", item))
        }
    </div>
}
else{
    <h3 class="text-danger">Không tìm thấy thông tin người dùng.</h3>
}

DoAnTotNghiep/Views/Users/_Report.cshtml
@model List<DetailReportViewModel>
@using DoAnTotNghiep.Enum;


<div class="list">
    <h2> Danh sách báo cáo</h2>
    <div class="list-frame">
        @foreach(var item in Model)
        {
            <div class="report-item">
                <div>
                    <div>
                        @if (string.IsNullOrEmpty(item.User.ImageUrl))
                    {
                        <img src="~/Image/user.svg" class="avt" alt="Avatar @item.User.UserName"/>
                    }
                    else
                    {
                        <img src="@item.User.ImageUrl" class="avt" alt="Avatar @item.User.UserName" /> 
                    }
                    <span class="name">@item.User.UserName</span>
                    </div>
                </div>
                <div>
                    <h5 class="text-danger">Lí do:</h5>
                    <div class="content">@Html.Raw(item.Content.Replace("\n", "<br>"))</div>
                    <h5 class="text-danger">Tệp đính kèm:</h5>
                    <div class="list-img">
                        @for(var index = 0; index <= 4; index++)
                        {
                            @foreach(var image in item.Images)
                            {
                                <div class="item-img"><img src="@image.Data" class="img-view" /></div>   
                            }
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>